name: Deploy Dashboard to Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to Dashboard Folder
        env:
          DEPLOY_PATH: /home/umitkumbul/Dashboard/
        run: |
          mkdir -p ${{ env.DEPLOY_PATH }}
          rsync -av --delete ./ ${{ env.DEPLOY_PATH }}
          # Ensure Tailscale serve is still correctly pointed
          # Serving the whole directory instead of just index.html
          sudo tailscale serve --bg --set-path=/ ${{ env.DEPLOY_PATH }}
